name: Get database
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download IDA pro
      uses: i3h/download-release-asset@v1.0.0
      with:
        owner: bedrock-server-mods
        repo: ida-pro-images
        tag: latest
        file: ida.zip
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Download innoextract
      uses: i3h/download-release-asset@v1.0.0
      with:
        owner: dscharrer
        repo: innoextract
        tag: 1.8
        file: innoextract-1.8-windows.zip
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Install IDA pro
      run: |
        $IDA = "IDA PRO 7.2"
        $EXE = "x64_idapronw_hexx64w_181105_de455c480e11ef1ec91473028f4dd175.exe"
        $KEY = "install_key.txt"
        7z e ida.zip "$IDA/$EXE" "$IDA/$KEY"
        7z x innoextract*.zip *.exe
        del *.zip
        .\innoextract.exe $EXE --silent --exclude-temp --password-file $KEY
        del *.exe
        del $KEY
        mv app ida

    - name: testing
      run: |
        wget
        curl
      shell: bash
