name: Get database
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installing wine
      run: |
        sudo dpkg --add-architecture i386
        wget -O - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
        sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
        sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
        sudo apt install --install-recommends winehq-stable

    - name: Downloading IDA pro
      uses: i3h/download-release-asset@v1.0.0
      with:
        owner: bedrock-server-mods
        repo: ida-pro-images
        tag: latest
        file: ida.zip
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Download innoextract
      uses: i3h/download-release-asset@v1.0.0
      with:
        owner: dscharrer
        repo: innoextract
        tag: "1.8"
        file: innoextract-1.8-linux.tar.xz
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Installing IDA pro
      run: |
        set -ex

        IDA="IDA PRO 7.2"
        EXE="x64_idapronw_hexx64w_181105_de455c480e11ef1ec91473028f4dd175.exe"
        KEY="install_key.txt"

        7z e ida.zip "$IDA/$EXE" "$IDA/$KEY"

        tar -xJf innoextract-1.8-linux.tar.xz
        ./innoextract-1.8-linux/innoextract "$EXE" --silent --exclude-temp --password-file $KEY

        mv app ida
        rm -rf *.zip innoextract* "$EXE" "$KEY"
        ls -lah

        wget -q https://www.pastefile.com/download/phn98s -O bedrock_server
        wine ida/idat64.exe -B bedrock_server
