name: Get database
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download IDA pro
      uses: i3h/download-release-asset@v1.0.0
      with:
        owner: bedrock-server-mods
        repo: ida-pro-images
        tag: latest
        file: ida.zip
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Unpack IDA pro
      run: 7z e ida.zip

    - name: Run a multi-line script
      run: |
        wmic cpu get Name
        echo $env:UserName
        $PASSWORD=type .\install_key.txt
        echo $PASSWORD
        .\x64_idapronw_hexx64w_181105_de455c480e11ef1ec91473028f4dd175.exe /PASSWORD=$PASSWORD /VERYSILENT /LOG=.\log /SUPPRESSMSGBOXES
        echo $?
        echo "test" > "C:\Program Files\test"
        dir "C:\Program Files"
        dir
